CREATE DATABASE IF NOT EXISTS usermanual DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE usermanual;

CREATE TABLE IF NOT EXISTS categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  icon VARCHAR(50) DEFAULT '📁',
  description VARCHAR(500) DEFAULT '',
  sort INT DEFAULT 0,
  parent_id INT DEFAULT NULL,
  status TINYINT DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (parent_id) REFERENCES categories(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS articles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  category_id INT NOT NULL,
  title VARCHAR(200) NOT NULL,
  content_html TEXT,
  content_text LONGTEXT,
  cover_image VARCHAR(500) DEFAULT '',
  sort INT DEFAULT 0,
  status TINYINT DEFAULT 0,
  version INT DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS tags (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE,
  color VARCHAR(20) DEFAULT '#3b89ff',
  description VARCHAR(500) DEFAULT ''
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS article_tags (
  article_id INT NOT NULL,
  tag_id INT NOT NULL,
  PRIMARY KEY (article_id, tag_id),
  FOREIGN KEY (article_id) REFERENCES articles(id) ON DELETE CASCADE,
  FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS admin_users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Add color and description columns to existing tags table
ALTER TABLE tags ADD COLUMN IF NOT EXISTS color VARCHAR(20) DEFAULT '#3b89ff';
ALTER TABLE tags ADD COLUMN IF NOT EXISTS description VARCHAR(500) DEFAULT '';

-- Default admin password: admin123
INSERT INTO admin_users (username, password) VALUES ('admin', '$2a$10$fEVHWVdM9UiR3EpO8CG.ueCiC9K/PFx0bzhzfhIIe435crTczS7yC');
